apiVersion: v1
kind: Service
metadata:
  name: artifactory-upload
  namespace: artifactory
spec:
  selector:
    app: artifactory-upload
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP