apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory-upload
  namespace: artifactory
  labels:
    app: artifactory-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory-upload
  template:
    metadata:
      labels:
        app: artifactory-upload
    spec:
      shareProcessNamespace: true
      containers:
      - name: artifactory-upload
        image: artifactory-upload-image
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: artifactory-upload-config
        - secretRef:
            name: artifactory-upload-secret
        ports:
        - containerPort: 8080